version: '3.8'
services:
  web:
    build: .
    container_name: bank-statements
    environment:
      - port=${port}
      - host=${host_fastapi}
      - password=${password}
      - user=${user}
      - db_name=${db_name}
      - INIT_DB= ${INIT_DB}
    ports: 
      - "8000:8000"

  db:
    image: mysql:8.0
    container_name: bank-statements_db
    environment:
      - port=${port_1}
      - host=${host_mysql}
      - user=${user}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    ports:
      - "3307:3306"
